/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProposicoesRouteImport } from './routes/proposicoes'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ModeloDadosRouteImport } from './routes/modelo-dados'
import { Route as IaRouteImport } from './routes/ia'
import { Route as DeputadosRouteImport } from './routes/deputados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeputadosRankingRouteImport } from './routes/deputados_.ranking'

const ProposicoesRoute = ProposicoesRouteImport.update({
  id: '/proposicoes',
  path: '/proposicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloDadosRoute = ModeloDadosRouteImport.update({
  id: '/modelo-dados',
  path: '/modelo-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputadosRoute = DeputadosRouteImport.update({
  id: '/deputados',
  path: '/deputados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputadosRankingRoute = DeputadosRankingRouteImport.update({
  id: '/deputados_/ranking',
  path: '/deputados/ranking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/automacao': typeof AutomacaoRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/deputados': typeof DeputadosRoute
  '/ia': typeof IaRoute
  '/modelo-dados': typeof ModeloDadosRoute
  '/pipeline': typeof PipelineRoute
  '/proposicoes': typeof ProposicoesRoute
  '/deputados/ranking': typeof DeputadosRankingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/automacao': typeof AutomacaoRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/deputados': typeof DeputadosRoute
  '/ia': typeof IaRoute
  '/modelo-dados': typeof ModeloDadosRoute
  '/pipeline': typeof PipelineRoute
  '/proposicoes': typeof ProposicoesRoute
  '/deputados/ranking': typeof DeputadosRankingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/automacao': typeof AutomacaoRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/deputados': typeof DeputadosRoute
  '/ia': typeof IaRoute
  '/modelo-dados': typeof ModeloDadosRoute
  '/pipeline': typeof PipelineRoute
  '/proposicoes': typeof ProposicoesRoute
  '/deputados_/ranking': typeof DeputadosRankingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/automacao'
    | '/chatbot'
    | '/dashboard'
    | '/deputados'
    | '/ia'
    | '/modelo-dados'
    | '/pipeline'
    | '/proposicoes'
    | '/deputados/ranking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/automacao'
    | '/chatbot'
    | '/dashboard'
    | '/deputados'
    | '/ia'
    | '/modelo-dados'
    | '/pipeline'
    | '/proposicoes'
    | '/deputados/ranking'
  id:
    | '__root__'
    | '/'
    | '/apresentacao'
    | '/automacao'
    | '/chatbot'
    | '/dashboard'
    | '/deputados'
    | '/ia'
    | '/modelo-dados'
    | '/pipeline'
    | '/proposicoes'
    | '/deputados_/ranking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  AutomacaoRoute: typeof AutomacaoRoute
  ChatbotRoute: typeof ChatbotRoute
  DashboardRoute: typeof DashboardRoute
  DeputadosRoute: typeof DeputadosRoute
  IaRoute: typeof IaRoute
  ModeloDadosRoute: typeof ModeloDadosRoute
  PipelineRoute: typeof PipelineRoute
  ProposicoesRoute: typeof ProposicoesRoute
  DeputadosRankingRoute: typeof DeputadosRankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposicoes': {
      id: '/proposicoes'
      path: '/proposicoes'
      fullPath: '/proposicoes'
      preLoaderRoute: typeof ProposicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo-dados': {
      id: '/modelo-dados'
      path: '/modelo-dados'
      fullPath: '/modelo-dados'
      preLoaderRoute: typeof ModeloDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputados': {
      id: '/deputados'
      path: '/deputados'
      fullPath: '/deputados'
      preLoaderRoute: typeof DeputadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputados_/ranking': {
      id: '/deputados_/ranking'
      path: '/deputados/ranking'
      fullPath: '/deputados/ranking'
      preLoaderRoute: typeof DeputadosRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  AutomacaoRoute: AutomacaoRoute,
  ChatbotRoute: ChatbotRoute,
  DashboardRoute: DashboardRoute,
  DeputadosRoute: DeputadosRoute,
  IaRoute: IaRoute,
  ModeloDadosRoute: ModeloDadosRoute,
  PipelineRoute: PipelineRoute,
  ProposicoesRoute: ProposicoesRoute,
  DeputadosRankingRoute: DeputadosRankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
